config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  constraints(ClientDomainConstraint.new) do
    root to: "home#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users, path: '' do
      resources :mes, only: :index
      resources :addresses
      resources :invite_people, only: :index
      resources :lottery
      resources  :shop
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: "home#index"
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :users
      resources :items do
        put :start, :pause, :end, :cancel
      end
      resources :categories
      resources :bets do
        put :cancel
      end
      resources :winners do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers
      resources :orders do
        put :pay, :cancel
      end
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :city_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city_municipality
end

app/models/address/city_municipality.rb
class Address::CityMunicipality < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangays
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :city_municipalities
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :provinces
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :parent, class_name: "User", optional: true , counter_cache: :children_members
  has_many :children, class_name: "User", foreign_key: 'parent_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable



  enum role: { client: 0, admin: 1 }
  validates :phone_number, phone: { possible: true, allow_blank: true, types: [:voip, :mobile], countries: :ph }, length: { maximum: 13 }
  mount_uploader :image, ImageUploader

  has_many :addresses
  has_many :bets
  has_many :winners
  has_many :orders




end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :authenticate_user!, except: :index
  def index
    @users = User.client
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  def index
    @users = User.all
  end

  def check_admin
    raise ActionController::RoutingError.new('Not Found') unless current_user.admin?
  end
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.addresses.includes(:user, :region, :province, :city_municipality, :barangay)
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(add_params)
    @address.user = current_user
    if @address.save
      redirect_to users_addresses_path
    else
      render :new
    end
  end

  def edit ;end

  def update
    if @address.update(add_params)
      redirect_to users_addresses_path
    else
      render :edit
    end
  end

  def destroy
    if @address.destroy
      redirect_to users_addresses_path
    end
  end

  private

  def add_params
    params.require(:address).permit(:genre, :name, :street_address, :phone_number, :remark, :is_default, :address_region_id, :address_province_id, :address_city_municipality_id, :address_barangay_id)
  end

  def set_address
    @address = Address.find(params[:id])
  end
end

app/controllers/users/invite_people_controller.rb
class Users::InvitePeopleController < ApplicationController
  require "rqrcode"
  before_action :invite
  before_action :generate_qrcode

  def index;
  end

  private

  def invite
      @url = "#{request.base_url}/users/sign_up?promoter=#{current_user.email}"
  end

  def generate_qrcode
    qrcode = RQRCode::QRCode.new("#{@url}")

    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 6,
      standalone: true,
      use_path: true
    ).html_safe
  end
end

app/controllers/users/lottery_controller.rb
class Users::LotteryController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_item, only: :show

  def index
    @items = Item.where(status: :active, state: :starting)
    @items = @items.includes(:categories).where(categories: { name: params[:category] }) if params[:category]
    @categories = Category.all
  end

  def show
    @bet = Bet.new
    @user_bet = @item.bets.where(user: current_user, batch_count: @item.batch_count, item: @item)
  end

  def create
    @count_bet = params[:bet][:coins].to_i
    params[:bet][:coins] = 1
    @count_bet.times {
      @bet = Bet.new(bet_params)
      @bet.user = current_user
      @bet.item = Item.find(params[:item_id])
      @bet.batch_count = @bet.item.batch_count
      @bet.save!
    }
    flash[:notice] = 'Successfully Bet!'
    redirect_to users_lottery_path(@bet.item)
  end

  private

  def bet_params
    params.require(:bet).permit(:item_id, :coins)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users/mes_controller.rb
class Users::MesController < ApplicationController

  def index
    @orders = Order.where(user: current_user) if params[:filter_by] == 'orders'
    @lotteries = Bet.where(user: current_user) if params[:filter_by] == 'lotteries'
    @winners = Winner.where(user: current_user) if params[:filter_by] == 'winners'
    @invitations = User.where(parent: current_user) if params[:filter_by] == 'invitations'
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only:  [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    unless cookies[:promoter]
      cookies[:promoter] = params[:promoter]
    end
  end

  # POST /resource
  def create
    cookies[:promoter]
    params[:user][:parent_id] = User.find_by_email(cookies[:promoter])&.id
    super
  end

  # GET /resource/edit
  def edit
    super
    # flash[:notice]
  end

  # PUT /resource
  def update
    parameter = params[:user]
    if parameter[:current_password].present? || parameter[:password_confirmation].present? || parameter[:password].present?
      update_with_pass
      # flash[:notice] = ''
    else
      update_without_pass
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def params_with_pass
    params.require(:user).permit(:current_password, :password_confirmation, :password)
  end

  def params_without_pass
    params.require(:user).permit(:username, :phone_number, :image, :current_password, :password_confirmation, :password)
  end

  def update_without_pass
    if params[:user][:current_password].blank?
      resource.update_without_password(params_without_pass.except(:current_password))
      redirect_to me_path
    else
      render :edit
    end
  end

  def update_with_pass
    if resource.update_with_password(params_with_pass)
      redirect_to new_user_session_path
    else
      render :edit
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    added_attrs = [:parent_id, :email, :phone_number, :password, :password_confirmation, :children_members, :remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    change = [:email, :phone_number, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit(:account_update, keys: change)
  end



  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected



  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/shop_controller.rb
class Users::ShopController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    @offers = Offer.active
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @offer = Offer.active.find(params[:order][:offer_id])
    @order.user = current_user
    @order.amount = @offer.amount
    @order.coins = @offer.coin
    @order.genre = :deposit
    @order.state = :submitted
    if @order.save
      flash[:notice] = "Successfully Order"
      redirect_to users_shop_index_path
    else
      flash[:alert] = "Unsuccessful Order"
      redirect_to users_shop_index_path
    end
  end

    private

    def order_params
      params.require(:order).permit(:offer_id)
    end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/addresses_helper.rb
module Users::AddressesHelper
end

app/helpers/users/invite_people_helper.rb
module Users::InvitePeopleHelper
end

app/helpers/users/lottery_helper.rb
module Users::LotteryHelper
end

app/helpers/users/mes_helper.rb
module Users::MesHelper
end

app/helpers/users/shop_helper.rb
module Users::ShopHelper
end

app/views/users/addresses/_form.html.erb
<div class="card-body">
  <%= form_with model: @address, url: path, data: { controller: :location, turbo: false } do |form| %>
    <div class="container  mt-lg-4">
      <% if address.errors.any? %>
        <ul>
          <% address.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
      <% end %>
      </ul>
      <div>
        <ul class="nav nav-pills nav-justified mt-3 mb-3 text-start">
          <li class="nav-item text-start mx-2">
            <div class="mb-2">
              <% form.label :name %>
              <%= form.text_field :name, class: "form-control", placeholder: 'Full Name' %>
            </div>
            <div class="mb-2">
              <% form.label :phone_number %>
              <%= form.phone_field :phone_number, class: "form-control", placeholder: '+63***********' %>
            </div>
            <div class="mb-2">
              <% form.label :remark %>
              <%= form.text_area :remark, class: "form-control height-60", placeholder: 'Remark' %>
            </div>
            <p>
            <% Address.genres.keys.each do |genre| %>
            <div class="mb-2">
              <%= form.radio_button :genre, genre %>
              <%= form.label genre.to_sym %>
            </div>
            <% end %></p>
          </li>
          <li class="nav-item text-start mx-2">
            <div class="mb-2">
              <% form.label :street_address %>
              <%= form.text_field :street_address, class: "form-control", placeholder: 'Street/Building Name/Unit/Floor' %>
            </div>
            <div>
              <% form.label :address_region_id %>
              <%= form.collection_select :address_region_id,
                                         Address::Region.all, :id, :name,
                                         { prompt: 'Select Region' },
                                         data: { location_target: 'selectedRegionId', action: 'change->location#fetchProvinces' },
                                         class: "form-control" %>
            </div>
            <div>
              <% form.label :address_province_id %>
              <%= form.collection_select :address_province_id, [], nil, nil,
                                         { prompt: 'Select Province/District' },
                                         data: { location_target: 'selectProvinceId', action: 'change->location#fetchCityMunicipalities' },
                                         class: "form-control" %>
            </div>
            <div>
              <% form.label :address_city_municipality_id %>
              <%= form.collection_select :address_city_municipality_id, [], nil, nil,
                                         { prompt: 'Select City/Municipality' },
                                         data: { location_target: 'selectCityMunicipalityId', action: 'change->location#fetchBarangays' },
                                         class: "form-control" %>
            </div>
            <div class="mb-2">
              <% form.label :address_barangay_id %>
              <%= form.collection_select :address_barangay_id, [], nil, nil,
                                         { prompt: 'Select Brgy' },
                                         data: { location_target: 'selectBarangayId' }, class: "form-control" %>
            </div>
            <div class="mb-2">
              <%= form.label :is_default %>
              <%= form.check_box :is_default %>
            </div>
            <div class="mb-2">
              <%= form.submit 'Save', class:'btn btn-outline-primary' %>
            </div>
          </li>
        </ul>
  <% end %>
  </div>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/users/addresses/edit.html.erb
<h2>Edit Address: <%= @address.user.username %></h2>
<%= render partial: 'form', locals: { address: @address, path: users_address_path } %>
<%= link_to 'Back', users_addresses_path %>

app/views/users/addresses/index.html.erb
<div class="container">
  <div class="container mt-5">
    <h1>Address</h1>
    <div class="card">
      <div class="card-body">
        <table class="table table-hover table-primary text-center">
          <thead>
          <th>Full Name</th>
          <th>Phone Number</th>
          <th>Remarks</th>
          <th>Genre</th>
          <th>Street</th>
          <th colspan="2">Address</th>
          <th colspan="2">Action</th>

          </thead>
          <% @addresses.each do |address| %>
            <tbody>
            <tr>
              <td><%= address.name %></td>
              <td><%= address.phone_number %></td>
              <td><%= address.remark %></td>
              <td>
                <span class="btn btn-secondary" style="border-radius: 20px; padding: 0 8px 0 8px"><%= address.genre %></span>
              </td>
              <td><%= address.street_address %></td>
              <td><%= "#{address.barangay&.name}, #{address.city_municipality&.name}, #{address.province&.name}, #{address.region.name}" %></td>
              <% if address.is_default? %>
                <td><span class="btn btn-warning" style="border-radius: 12px; padding: 0 9px 0 9px">Default</span></td>
              <% else %>
                <td></td>
              <% end %>
              <td><%= link_to 'Edit', edit_users_address_path(address), class: "btn btn-outline-secondary" %></td>
              <td><%= button_to 'Delete', users_address_path(address), method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn btn-outline-danger" %></td>
            </tr>
            </tbody>
          <% end %>
        </table>
        <%= link_to 'New address', new_users_address_path, class: "btn btn-dark float-end" %>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>