config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  constraints(ClientDomainConstraint.new) do
    root to: "home#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users, path: '' do
      resources :mes, only: :index
      resources :addresses
      resources :invite_people, only: :index
      resources :lottery
      resources  :shop
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: "home#index"
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :users
      resources :items do
        put :start, :pause, :end, :cancel
      end
      resources :categories
      resources :bets do
        put :cancel
      end
      resources :winners do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers
      resources :orders do
        put :pay, :cancel
      end
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :city_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  belongs_to :user
  belongs_to :offer
  after_create :assign_serial_number

  enum genre: { deposit: 0, increase: 1, deduct: 2, bonus: 3, share: 4 }

  aasm column: :state do
    state :pending, initial: true
    state :submitted, :cancelled, :paid

    event :submit do
      transitions from: :pending, to: :submitted
    end

    event :cancel do
      transitions from: [:pending, :submitted], to: :cancelled
      transitions from: :paid, to: :cancelled, after: [:cancel_deduction, :decrease_total_deposit], guard: :enough_coins?
    end

    event :pay do
      transitions from: :submitted, to: :paid, after: [:deduction_pay, :increase_total_deposit]
    end
  end

  def deduction_pay
    if deduct?
      self.user.update(coins: self.user.coins - self.coins)
    else
      self.user.update(coins: self.user.coins + self.coins)
    end
  end

  def cancel_deduction
    if deduct?
      self.user.update(coins: self.user.coins + self.coins)
    else
      self.user.update(coins: self.user.coins - self.coins)
    end
  end

  def decrease_total_deposit
    if deposit?
      self.user.update(total_deposit: self.user.total_deposit - self.amount)
    end
  end

  def increase_total_deposit
    if deposit?
      self.user.update(total_deposit: self.user.total_deposit + self.amount)
    end
  end

  def assign_serial_number
    number_count = Order.where(user_id: user.id).count.to_s.rjust(4, '0')
    self.update!(serial_number: "#{Time.current.strftime("%y%m%d")}-#{id}-#{user.id}-#{number_count}")
  end

  def enough_coins?
    self.user.coins >= coins
  end

  def enough_total_deposit?
    if deposit?
      amount >= 1
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, only: [:pay, :cancel]

  def index
    @orders = Order.includes(:user, :offer).all
    @orders = @orders.where(serial_number: params[:serial_number]) if params[:serial_number].present?
    @orders = @orders.where(user: { email: params[:user_email] }) if params[:user_email].present?
    @orders = @orders.where(state: params[:state]) if params[:state].present?
    @orders = @orders.where(genre: params[:genre]) if params[:genre].present?
    @orders = @orders.where(offer: {name: params[:name] }) if params[:name].present?
  end

  def pay
    if @order.may_pay?
      @order.pay!
      flash[:notice] = "Successfully Paid"
      redirect_to admin_orders_path
    else
      flash[:alert] = "Unsuccessful Paid Transaction!"
      redirect_to admin_orders_path
    end
  end

  def cancel
    if @order.may_cancel?
      @order.cancel!
      flash[:notice] = "Successfully Cancelled"
      redirect_to admin_orders_path
    else
      flash[:alert] = "Unsuccessful Cancelled Transaction!"
    end
    end

    private

    def set_order
      @order = Order.find(params[:order_id])
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <h2><strong>Order Lists</strong></h2>
  <div class="card text-center table-responsive">
    <div class="card-body">
      <%= form_tag({ url: admin_orders_path }, method: :get , data: { turbo: false }) do %>
        <ul class="nav nav-pills nav-justified mt-3 mb-2 text-start">
          <div class="col-12">
            <%= label_tag 'Serial Number' %>
            <%= text_field_tag :serial_number, '', placeholder: "Serial Number", class: "form-control" %>
          </div>

          <li class="nav-item text-start mx-2 mt-3">
            <div class="mb-3">
              <%= label_tag 'Email' %>
              <%= text_field_tag :user_email, '', placeholder: "Email", class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= label_tag 'Genre' %>
              <%= select_tag :genre, options_for_select(Order.genres.keys.map { |key| [key.humanize, key] }, params[:genre]), { prompt: 'Choose Genre', class: "form-control form-select" } %>
            </div>

          <li class="nav-item text-start mx-2 mt-3">
            <div class="mb-3">
              <%= label_tag :state %>
              <%= select_tag :state, options_for_select(Order.aasm.states.map(&:name)), { prompt: 'Choose State', class: "form-control form-select" } %>
            </div>

            <div class="mb-3">
              <%= label_tag 'Offer' %>
              <%= select_tag :offer, options_for_select(Offer.genres.keys.map { |key| [key.humanize, key] }, params[:offer]), { prompt: 'Choose Offer', class: "form-control form-select" } %>
            </div>

            <div class="text-center">
              <%= submit_tag :Search, class: "btn btn-info mt-2" %>
              <%= link_to "Cancel", admin_offers_path, class: 'mx-2 btn btn-info mt-2' %>
            </div>
          </li>

          <li class="nav-item text-start mx-2 mt-3">

            <div class="mb-3">
              <%= label_tag 'Create Date' %>
              <%= datetime_field_tag :create_at, '', class: "form-control", value: params[:create_at] %>
            </div>

            <div class="mb-3">
              <%= label_tag 'End Date' %>
              <%= datetime_field_tag :end, '', class: "form-control", value: params[:end] %>
            </div>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
  <table class="table table-hover table-primary text-center mt-3">
    <thead>
    <th>Serial_number</th>
    <th>Email</th>
    <th>Offer</th>
    <th>Genre</th>
    <th>Amount</th>
    <th>Coins</th>
    <th>State</th>
    <th>Created_at</th>
    <th colspan="2">Action</th>
    </thead>
    <div class="container">
      <% @orders&.each do |order| %>
        <div class="table table-warning">
          <tr>
            <td><%= order.serial_number %></td>
            <td><span class="btn btn-success" style="border-radius: 20px; padding: 0 8px 0 8px"><%= order.offer.name %></span></td>
            <td><%= order.user&.email %></td>
            <td><span class="btn btn-success" style="border-radius: 20px; padding: 0 8px 0 8px"><%= order.genre %></span></td>
            <td><%= order.amount %></td>
            <td><%= order.coins %></td>
            <td><span class="btn btn-success" style="border-radius: 20px; padding: 0 8px 0 8px"><%= order.state %></span></td>
            <td><%= order.created_at %></td>
            <td><%= button_to 'Pay', admin_order_pay_path(order.id), method: :put, class: 'btn btn-warning' if order.may_pay? %></td>
            <td><%= button_to 'Cancel', admin_order_cancel_path(order.id), method: :put, :onclick => "return confirm('Are you sure you want to cancel?')", class: 'btn btn-outline-danger' if order.may_cancel? %></td>
          </tr>
        </div>
      <% end %>
    </div>
  </table>
</div>