config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  constraints(ClientDomainConstraint.new) do
    root to: "home#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users, path: '' do
      resources :mes, only: :index
      resources :addresses
      resources :invite_people, only: :index
      resources :lottery
      resources  :shop
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: "home#index"
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :users
      resources :items do
        put :start, :pause, :end, :cancel
      end
      resources :categories
      resources :bets do
        put :cancel
      end
      resources :winners do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers
      resources :orders do
        put :pay, :cancel
      end
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :city_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/winner.rb
class Winner < ApplicationRecord
  include AASM
  belongs_to :item
  belongs_to :bet
  belongs_to :user
  belongs_to :address, optional: true
  belongs_to :admin, class_name: "User", optional: true

  aasm column: :state do
    state :won, :claimed, :submitted, :paid, :shipped, :delivered, :shared, :published, :remove, :published

    event :claim do
      transitions from: :won, to: :claimed
    end

    event :submit do
      transitions from: :claimed, to: :submitted
    end

    event :pay do
      transitions from: :submitted, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipped
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :share do
      transitions from: :delivered, to: :shared
    end

    event :publish do
      transitions from: [:share, :remove_published], to: :published
    end

    event :remove_publish do
      transitions from: :published, to: :remove_published
    end
  end
end

app/controllers/admin/winners_controller.rb
class Admin::WinnersController < AdminController
  before_action :winner_params, only: [:submit, :pay, :ship, :deliver, :publish, :remove_publish]

  def index
    @winners = Winner.includes(:user, :item, :bet).all
    @winner = @winners.where(bet: params[:serial_number]) if params[:serial_number].present?
    @bets = @bets.where(user: { email: params[:user_email] }) if params[:user_email].present?
    @bets = @bets.where(state: params[:state]) if params[:state].present?
  end

  def submit
    @winner.submit!
    flash[:notice] = "Submitted"
    redirect_to admin_winners_path
  end

  def pay
    @winner.pay!
    flash[:notice] = "Successfully paid"
    redirect_to admin_winners_path
  end

  def ship
    @winner.ship!
    flash[:notice] = "Is ready to ship"
    redirect_to admin_winners_path
  end

  def deliver
    @winner.deliver!
    flash[:notice] = "The prize is ready to deliver"
    redirect_to admin_winners_path
  end

  def publish
    @winner.publish!
    flash[:notice] = "Published"
    redirect_to admin_winners_path
  end

  def remove_publish
    @winner.remove_publish!
    flash[:notice] = "Remove the publish"
    redirect_to admin_winners_path
  end

  private

  def winner_params
    @winner = Winner.find(params[:winner_id])

  end
end

app/helpers/admin/winners_helper.rb
module Admin::WinnersHelper
end

app/views/admin/winners/index.html.erb
<div class="container">
  <%= form_tag({ url: admin_winners_path }, method: :get) do %>
    <div class="row">
      <div class="col-12">
        <%= label_tag :serial_number %>
        <%= text_field_tag :serial_number, params[:serial_number], class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= label_tag :email %>
        <%= text_field_tag :email, params[:email], class: 'form-control' %>
      </div>
      <div class="col-6">
        <%= label_tag :state %>
        <%= select_tag :state, options_for_select(Winner.aasm.states.map(&:name), params[:state]), { prompt: "Select State", class: 'form-control' } %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= label_tag :create_date %>
        <%= date_field_tag :created_at, params[:created_at], class: 'form-control' %>
      </div>
      <div class="col-6">
        <%= label_tag :end_date %>
        <%= date_field_tag :ended_at, params[:ended_at], class: 'form-control' %>
      </div>
    </div>
    <%= submit_tag :Search, class: 'btn btn-dark mt-2' %><%= link_to "Cancel", admin_winners_path, class: 'mx-2 btn btn-dark mt-2' %>
  <% end %>
  <hr>
  <div style="overflow: auto;">
    <div class="card-body">
      <table class="table table-hover table-primary text-center">
        <th>Serial Number</th>
        <th>Item Name</th>
        <th>Email</th>
        <th>State</th>
        <th>Date</th>
        <th colspan="3">Action</th>
        <% @winners.each do |winner| %>
          <tbody>
          <tr>
            <td><%= winner.bet.serial_number %></td>
            <td><%= winner.item.name %></td>
            <td><%= winner.user.email %></td>
            <td><span class="btn btn-success" style="border-radius: 20px; padding: 0 8px 0 8px"><%= winner.state %></td>
            <td><%= winner.created_at %></td>
            <td>
              <%= button_to "Submit", admin_winner_submit_path(winner), method: :put, class: 'btn btn-warning' if winner.may_submit? %>
              <%= button_to "Pay", admin_winner_pay_path(winner), method: :put, class: 'btn btn-warning' if winner.may_pay? %>
              <%= button_to "Ship", admin_winner_ship_path(winner), method: :put, class: 'btn btn-warning' if winner.may_ship?  %></td>
        <% end %>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>