config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  constraints(ClientDomainConstraint.new) do
    root to: "home#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    namespace :users, path: '' do
      resources :mes, only: :index
      resources :addresses
      resources :invite_people, only: :index
      resources :lottery
      resources  :shop
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root to: "home#index"
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      resources :users
      resources :items do
        put :start, :pause, :end, :cancel
      end
      resources :categories
      resources :bets do
        put :cancel
      end
      resources :winners do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers
      resources :orders do
        put :pay, :cancel
      end
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :city_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { where(deleted_at: nil) }
  validates :name, presence: true

  has_many :item_category_ships
  has_many :item, through: :item_category_ships
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    before_action :set_category, only: [:edit, :update, :destroy]

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = 'Successfully saved'
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def edit ;end

    def update
      if @category.update(category_params)
        redirect_to admin_categories_path
      else
        render :edit
      end
    end

    def destroy
      @category.destroy
      if @category.deleted_at
        flash[:notice] = "Successfully Deleted"
      else
        flash[:alert] = "The item cannot be delete"
        redirect_to admin_categories_path
      end
    end

    private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit( :name)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="card-body">
  <%= form_with model: category, url: path, data: { turbo: false } do |form| %>
    <div class="container  mt-lg-4">
      <% if category.errors.any? %>
        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
          <% end %>
          </ul>
          <div class="card-body">
            <div class="mb-3">
              <% form.label :name %>
              <%= form.text_field :name, class: "form-control", placeholder: 'Item Name' %>
            </div>
            <div class="mb-2">
              <%= form.submit 'Save', class:'btn btn-outline-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<%= render 'layouts/adminheader' %>
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: admin_category_path} %>

app/views/admin/categories/index.html.erb
<%= render 'layouts/adminheader' %>
<div class="container">
  <div class="container mt-5">
    <h1>Item</h1>
    <div class="card">
      <div class="card-body">
        <table class="table table-hover table-primary text-center">
          <thead>
          <th>Name</th>
          <th colspan="2">Action</th>

          </thead>
          <% @categories.each do |category| %>
            <tbody>
            <tr>
              <td><%= category.name %></td>
              <td><%= link_to 'Edit', edit_admin_category_path(category), class: "btn btn-outline-secondary" %></td>
              <td><%= button_to 'Delete', admin_category_path(category), method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn btn-outline-danger" %></td>
            </tr>
            </tbody>
          <% end %>
        </table>
        <%= link_to 'New Item', new_admin_category_path, class: "btn btn-dark float-end" %>
      </div>
    </div>
  </div>
</div>
</thead>